### 1. The total number of crimes recorded:

In [1]:
df_1 = _deepnote_execute_sql('SELECT \n  DISTINCT(\n    COUNT(CASE_NUMBER)\n  ) AS NUMBER_OF_CRIMES \nFROM \n  ChicagoCrimeData.csv\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_1

   NUMBER_OF_CRIMES
0               533

### 2. Community areas with per capita income (average per-person income for an area) less than 11000

In [2]:
df_2 = _deepnote_execute_sql('SELECT \n  COMMUNITY_AREA_NAME, \n  PER_CAPITA_INCOME \nFROM \n  ChicagoCensusData.csv \nWHERE \n  PER_CAPITA_INCOME < 11000\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_2

  COMMUNITY_AREA_NAME  PER_CAPITA_INCOME
0  West Garfield Park              10934
1      South Lawndale              10402
2         Fuller Park              10432
3           Riverdale               8201

### 3. All case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [3]:
df_3 = _deepnote_execute_sql('SELECT \n  CASE_NUMBER \nFROM \n  ChicagoCrimeData.csv \nWHERE \n  DESCRIPTION LIKE \'%MINOR%\'\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3

  CASE_NUMBER
0    HL266884
1    HK238408

### 4. All kidnapping crimes involving a child

In [4]:
df_4 = _deepnote_execute_sql('SELECT \n  CASE_NUMBER \nFROM \n  ChicagoCrimeData.csv \nWHERE \n  DESCRIPTION LIKE \'%CHILD%\' \n  AND PRIMARY_TYPE = \'KIDNAPPING\'', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_4

  CASE_NUMBER
0    HN144152

### 5. Types of crimes recorded at schools

In [7]:
df_5 = _deepnote_execute_sql('SELECT \n  DISTINCT (PRIMARY_TYPE), \n  LOCATION_DESCRIPTION \nFROM \n  ChicagoCrimeData.csv \nWHERE \n  LOCATION_DESCRIPTION LIKE \'%SCHOOL%\'', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_5

             PRIMARY_TYPE       LOCATION_DESCRIPTION
0                 BATTERY    SCHOOL, PUBLIC, GROUNDS
1                 BATTERY   SCHOOL, PUBLIC, BUILDING
2         CRIMINAL DAMAGE    SCHOOL, PUBLIC, GROUNDS
3               NARCOTICS    SCHOOL, PUBLIC, GROUNDS
4               NARCOTICS   SCHOOL, PUBLIC, BUILDING
5                 ASSAULT    SCHOOL, PUBLIC, GROUNDS
6       CRIMINAL TRESPASS    SCHOOL, PUBLIC, GROUNDS
7  PUBLIC PEACE VIOLATION  SCHOOL, PRIVATE, BUILDING
8  PUBLIC PEACE VIOLATION   SCHOOL, PUBLIC, BUILDING

### 6. The average safety score in Chicago public schools

In [9]:
df_6 = _deepnote_execute_sql('SELECT \n  AVG(SAFETY_SCORE) AS AVERAGE_SAFETY_SCORE \nFROM \n  ChicagoPublicSchools.csv', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_6

   AVERAGE_SAFETY_SCORE
0             49.504873

### 7. Top 5 community areas with highest % of households below poverty line (minimum level of income needed to secure the necessities of life)

In [12]:
df_7 = _deepnote_execute_sql('SELECT \n  COMMUNITY_AREA_NAME, \n  PERCENT_HOUSEHOLDS_BELOW_POVERTY \nFROM \n  ChicagoCensusData.csv \nORDER BY \n  PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC\nLIMIT 5  ', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_7

  COMMUNITY_AREA_NAME  PERCENT_HOUSEHOLDS_BELOW_POVERTY
0           Riverdale                              56.5
1         Fuller Park                              51.2
2           Englewood                              46.6
3      North Lawndale                              43.1
4  East Garfield Park                              42.4

### 8. The community area that is most crime prone

In [23]:
df_8 = _deepnote_execute_sql('SELECT \n  COMMUNITY_AREA_NUMBER, \n  COUNT(COMMUNITY_AREA_NUMBER) AS CRIME_FREQUENCY \nFROM \n  ChicagoCrimeData.csv \nGROUP BY \n  COMMUNITY_AREA_NUMBER \nORDER BY \n  COUNT(COMMUNITY_AREA_NUMBER) DESC\nLIMIT 1', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_8

   COMMUNITY_AREA_NUMBER  CRIME_FREQUENCY
0                     25               43

### 9. The community area with the highest hardship index

In [26]:
df_9 = _deepnote_execute_sql('SELECT \n  COMMUNITY_AREA_NAME, \n  HARDSHIP_INDEX \nFROM \n  ChicagoCensusData.csv \nWHERE \n  HARDSHIP_INDEX = (\n    SELECT \n      MAX(HARDSHIP_INDEX) \n    FROM \n      ChicagoCensusData.csv\n  )', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_9

  COMMUNITY_AREA_NAME  HARDSHIP_INDEX
0           Riverdale              98

### 10. The Community Area with the most crime

In [29]:
df_10 = _deepnote_execute_sql('SELECT \n  COMMUNITY_AREA_NAME \nFROM \n  ChicagoCensusData.csv \nWHERE \n  COMMUNITY_AREA_NUMBER = (\n    SELECT \n    COMMUNITY_AREA_NUMBER \n    FROM \n      ChicagoCrimeData.csv \n    GROUP BY \n      COMMUNITY_AREA_NUMBER \n    ORDER BY \n      COUNT(COMMUNITY_AREA_NUMBER) DESC\n    LIMIT 1\n  )', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_10

  COMMUNITY_AREA_NAME
0              Austin

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a212f2cd-0f1e-4cf2-8c07-297c193091fa' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>